import json
from typing import Any, Dict, Union

from src.repository.cloud_storage_repository import CloudStorageRepository
from src.repository.repository import Repository
from src.server.agent.config import PROJECT_ID
from src.utils.get_video_id import get_video_id


class ReadVideoTranscriptionTool:
    """
    Cloud Storage 에 저장된 동영상의 트랜스크립션(JSON)을 읽어 옵니다.
    """
    name = "read_video_transcription"
    description = (
        "Return transcription (as JSON) for a video.",
        "transcription is a JSON file that contains transcription information. this file has information about the video's transcription, including the start and end time of each transcription.",
        "transcription file is generated by AI model so it is not 100% accurate.",
        "Output: transcription text"
    )
    parameters = {
        "type": "object",
        "properties": {
            "video_id": {
                "type": "string",
                "description": "the id of the video file"
            }
        },
        "required": ["video_id"]
    }

    def __init__(self):
        self.repository: Repository = CloudStorageRepository()

    def call(self, video_id: str) -> str:
        transcription_bytes = self.repository.get_video_transcription(PROJECT_ID, video_id)
        transcription_json = json.loads(transcription_bytes)
        transcription = transcription_json["transcription"]

        return json.dumps(transcription, ensure_ascii=False)
        
    @staticmethod
    def as_tool() -> Dict[str, Any]:
        """Convert the tool to a LangGraph-compatible tool format."""
        return {
            "type": "function",
            "function": {
                "name": ReadVideoTranscriptionTool.name,
                "description": "\n".join(ReadVideoTranscriptionTool.description),
                "parameters": ReadVideoTranscriptionTool.parameters
            }
        }
