import json
from typing import Any, Dict, Union

from src.repository.cloud_storage_repository import CloudStorageRepository
from src.repository.repository import Repository
from src.server.agent.config import PROJECT_ID
from src.utils.get_video_id import get_video_id


class ReadVideoTranscriptionOverviewTool:
    name = "read_video_transcription_overview"
    description = (
        "Return transcription overview for a video.",
        "transcription overview is a text file that contains transcription information. this information doesn't contain start and end time of each transcription.",
        "transcription file is generated by AI model so it is not 100% accurate.",
        "Output: transcription text(string)"
    )
    parameters = {
        "type": "object",
        "properties": {
            "video_id": {
                "type": "string",
                "description": "the id of the video file"
            }
        },
        "required": ["video_id"]
    }

    def __init__(self):
        self.repository: Repository = CloudStorageRepository()

    def call(self, video_id: str) -> str:
        transcription_bytes = self.repository.get_video_transcription(PROJECT_ID, video_id)
        transcription_json = json.loads(transcription_bytes)
        transcription_overview = transcription_json["transcription"]
        return transcription_overview
        
    @staticmethod
    def as_tool() -> Dict[str, Any]:
        """Convert the tool to a LangGraph-compatible tool format."""
        return {
            "type": "function",
            "function": {
                "name": ReadVideoTranscriptionOverviewTool.name,
                "description": "\n".join(ReadVideoTranscriptionOverviewTool.description),
                "parameters": ReadVideoTranscriptionOverviewTool.parameters
            }
        }
